# Generated by Django 5.2.4 on 2025-07-21 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="archivo",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Archivo",
                "verbose_name_plural": "Archivos",
            },
        ),
        migrations.AlterModelOptions(
            name="registrofonasa",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Registro FONASA",
                "verbose_name_plural": "Registros FONASA",
            },
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="aceptado_rechazado",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Aceptado/Rechazado"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="autorizado",
            field=models.BooleanField(default=False, verbose_name="Autorizado"),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="codigo_centro_destino",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código centro destino"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="codigo_centro_procedencia",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código centro procedencia"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="codigo_comuna_destino",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código comuna destino"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="codigo_comuna_procedencia",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Código comuna procedencia"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="exbloqueado",
            field=models.BooleanField(default=False, verbose_name="Ex-bloqueado"),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="motivo",
            field=models.TextField(blank=True, verbose_name="Motivo"),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="nombre_centro_destino",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre centro destino"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="nombre_centro_procedencia",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre centro procedencia"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="nombre_comuna_destino",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre comuna destino"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="nombre_comuna_procedencia",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nombre comuna procedencia"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="nuevo_inscrito",
            field=models.BooleanField(default=False, verbose_name="Nuevo inscrito"),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="rechazado_fallecido",
            field=models.BooleanField(
                default=False, verbose_name="Rechazado fallecido"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="rechazado_previsional",
            field=models.BooleanField(
                default=False, verbose_name="Rechazado previsional"
            ),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="traslado_negativo",
            field=models.BooleanField(default=False, verbose_name="Traslado negativo"),
        ),
        migrations.AddField(
            model_name="registrofonasa",
            name="traslado_positivo",
            field=models.BooleanField(default=False, verbose_name="Traslado positivo"),
        ),
        migrations.AlterField(
            model_name="archivo",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="archivo",
            name="estado",
            field=models.CharField(
                choices=[
                    ("pendiente", "Pendiente"),
                    ("procesado", "Procesado"),
                    ("error", "Error"),
                ],
                default="pendiente",
                max_length=12,
                verbose_name="Estado de Procesamiento",
            ),
        ),
        migrations.AlterField(
            model_name="archivo",
            name="fecha_corte",
            field=models.DateField(db_index=True, verbose_name="Fecha de Corte"),
        ),
        migrations.AlterField(
            model_name="archivo",
            name="filename",
            field=models.CharField(max_length=255, verbose_name="Nombre original"),
        ),
        migrations.AlterField(
            model_name="archivo",
            name="total_registros",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Total registros"
            ),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="apellido_materno",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Apellido materno"
            ),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="apellido_paterno",
            field=models.CharField(max_length=100, verbose_name="Apellido paterno"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="archivo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="registros",
                to="api.archivo",
                verbose_name="Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="cod_centro",
            field=models.CharField(max_length=10, verbose_name="Código centro"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="dv",
            field=models.CharField(max_length=1, verbose_name="Dígito verificador"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="fecha_corte",
            field=models.DateField(verbose_name="Fecha de Corte"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="fecha_nacimiento",
            field=models.DateField(verbose_name="Fecha de nacimiento"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="genero",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino")],
                max_length=1,
                verbose_name="Género",
            ),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="nombre_centro",
            field=models.CharField(max_length=255, verbose_name="Nombre centro"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="nombres",
            field=models.CharField(max_length=255, verbose_name="Nombres"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="run",
            field=models.CharField(max_length=12, verbose_name="RUN (sin DV)"),
        ),
        migrations.AlterField(
            model_name="registrofonasa",
            name="tramo",
            field=models.CharField(
                blank=True, max_length=10, verbose_name="Tramo FONASA"
            ),
        ),
        migrations.AddIndex(
            model_name="registrofonasa",
            index=models.Index(fields=["run", "dv"], name="api_registr_run_3f3ebf_idx"),
        ),
        migrations.AddIndex(
            model_name="registrofonasa",
            index=models.Index(
                fields=["fecha_corte"], name="api_registr_fecha_c_e4e4ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrofonasa",
            index=models.Index(
                fields=["cod_centro"], name="api_registr_cod_cen_32ad86_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrofonasa",
            index=models.Index(
                fields=["nuevo_inscrito"], name="api_registr_nuevo_i_dabd40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrofonasa",
            index=models.Index(
                fields=["traslado_positivo"], name="api_registr_traslad_b7d4fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="registrofonasa",
            index=models.Index(
                fields=["traslado_negativo"], name="api_registr_traslad_5d4d35_idx"
            ),
        ),
    ]
